from flask import Flask, render_template_string, request, redirect
import sqlite3
                                                                             app = Flask(__name__)                                                        
HTML_TEMPLATE = '''                                                          <!DOCTYPE html>
<html dir="rtl">                                                             <head>
    <meta charset="UTF-8">                                                       <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Personal OS - Yonatan</title>                                         <style>                                                                          body { font-family: sans-serif; background: #121212; color: #e0e0e0; padding: 20px; line-height: 1.6; }                                                   .card { background: #1e1e1e; padding: 15px; border-radius: 12px; margin-bottom: 15px; border: 1px solid #333; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }                                                                                 input, textarea, button { width: 100%; padding: 12px; margin: 8px 0; border-radius: 8px; border: 1px solid #444; box-sizing: border-box; }                input, textarea { background: #2a2a2a; color: white; }                       button { background: #007bff; color: white; font-weight: bold; border: none; cursor: pointer; transition: 0.3s; }                                         button:hover { background: #0056b3; }                                        .journal-entry { border-right: 4px solid #007bff; padding-right: 10px; font-style: italic; }                                                              h1, h2 { color: #007bff; text-align: center; }                               .tabs { display: flex; justify-content: space-around; margin-bottom: 20px; }                                                                          </style>                                                                 </head>
<body>                                                                           <h1>מערכת הפעלה אישית</h1>                                               
    <div class="card">                                                               <h2>משימה חדשה</h2>
        <form action="/add_mission" method="post">                                       <input type="text" name="goal" placeholder="מה היעד שלך?" required>                                                                                       <input type="text" name="o1" placeholder="אופציה/סיכון 1" required>                                                                                       <input type="text" name="o2" placeholder="אופציה/סיכון 2" required>
            <input type="text" name="o3" placeholder="אופציה/סיכון 3" required>
            <button type="submit">שמור תכנון</button>                                </form>
    </div>                                                                   
    <div class="card">                                                               <h2>שיחה עם השמיים</h2>
        <form action="/add_journal" method="post">                                       <textarea name="entry" rows="3" placeholder="מה על ליבך?" required></textarea>                                                                            <button type="submit" style="background: #28a745;">שמור מחשבה</button>                                                                                </form>
    </div>                                                                   
    <hr>                                                                         <h2>הנתונים שלך</h2>
    {% for m in missions %}                                                      <div class="card">
        <strong>{{ m[2] }}</strong><br>                                              <small style="color: #888;">{{ m[1] }}</small><br>
        <div style="margin-top: 5px;">1. {{ m[3] }} | 2. {{ m[4] }} | 3. {{ m[5] }}</div>                                                                     </div>
    {% endfor %}                                                                                                                                              {% for j in journal %}
    <div class="card journal-entry">                                                 <small style="color: #888;">{{ j[1] }} - מחשבה</small><br>                   {{ j[2] }}                                                               </div>                                                                       {% endfor %}                                                             </body>
</html>                                                                      '''                                                                          
def get_db():                                                                    conn = sqlite3.connect('my_private_data.db')
    return conn                                                                                                                                           @app.route('/')
def index():                                                                     conn = get_db()
    cursor = conn.cursor()                                                       cursor.execute("SELECT * FROM missions ORDER BY id DESC")
    missions = cursor.fetchall()
    cursor.execute("SELECT * FROM journal ORDER BY id DESC")                     journal = cursor.fetchall()                                                  conn.close()                                                                 return render_template_string(HTML_TEMPLATE, missions=missions, journal=journal)                                                                      
@app.route('/add_mission', methods=['POST'])                                 def add_mission():                                                               conn = get_db()                                                              cursor = conn.cursor()                                                       cursor.execute("INSERT INTO missions (timestamp, goal, opt1, opt2, opt3) VALUES (datetime('now', 'localtime'), ?, ?, ?, ?)",                                             (request.form['goal'], request.form['o1'], request.form['o2'], request.form['o3']))                                                        conn.commit()                                                                conn.close()                                                                 return redirect('/')                                                                                                                                  @app.route('/add_journal', methods=['POST'])                                 def add_journal():                                                               conn = get_db()                                                              cursor = conn.cursor()
    cursor.execute("INSERT INTO journal (timestamp, entry) VALUES (datetime('now', 'localtime'), ?)", (request.form['entry'],))                               conn.commit()                                                                conn.close()                                                                 return redirect('/')
                                                                             if __name__ == '__main__':                                                       app.run(host='0.0.0.0', port=5000)                                                                                                                    0
